[2024-05-02T22:57:53.459+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-02T22:57:53.974+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 17_dag_buah.create_buah_table scheduled__2024-04-24T00:00:00+00:00 [queued]>
[2024-05-02T22:57:54.157+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 17_dag_buah.create_buah_table scheduled__2024-04-24T00:00:00+00:00 [queued]>
[2024-05-02T22:57:54.177+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-05-02T22:57:54.712+0000] {taskinstance.py:2327} INFO - Executing <Task(PostgresOperator): create_buah_table> on 2024-04-24 00:00:00+00:00
[2024-05-02T22:57:54.792+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=331) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-02T22:57:54.816+0000] {standard_task_runner.py:63} INFO - Started process 344 to run task
[2024-05-02T22:57:54.828+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', '17_dag_buah', 'create_buah_table', 'scheduled__2024-04-24T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/17_DAG_eks.py', '--cfg-path', '/tmp/tmpobvfsbcn']
[2024-05-02T22:57:54.843+0000] {standard_task_runner.py:91} INFO - Job 5: Subtask create_buah_table
[2024-05-02T22:57:55.176+0000] {task_command.py:426} INFO - Running <TaskInstance: 17_dag_buah.create_buah_table scheduled__2024-04-24T00:00:00+00:00 [running]> on host bb10af88434b
[2024-05-02T22:57:56.057+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ERISTA' AIRFLOW_CTX_DAG_ID='17_dag_buah' AIRFLOW_CTX_TASK_ID='create_buah_table' AIRFLOW_CTX_EXECUTION_DATE='2024-04-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-24T00:00:00+00:00'
[2024-05-02T22:57:56.076+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-02T22:57:56.079+0000] {sql.py:276} INFO - Executing: 
        CREATE TABLE IF NOT EXISTS buah (
            id SERIAL PRIMARY KEY,
            name VARCHAR(50) NOT NULL,
            calories DECIMAL NOT NULL,
            fat DECIMAL NOT NULL,
            sugar DECIMAL NOT NULL,
            carbohydrates DECIMAL NOT NULL,
            protein DECIMAL NOT NULL
        );
    
[2024-05-02T22:57:56.168+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2024-05-02T22:57:56.229+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2024-05-02T22:57:57.132+0000] {sql.py:457} INFO - Running statement: 
        CREATE TABLE IF NOT EXISTS buah (
            id SERIAL PRIMARY KEY,
            name VARCHAR(50) NOT NULL,
            calories DECIMAL NOT NULL,
            fat DECIMAL NOT NULL,
            sugar DECIMAL NOT NULL,
            carbohydrates DECIMAL NOT NULL,
            protein DECIMAL NOT NULL
        );
    , parameters: None
[2024-05-02T22:57:58.175+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-02T22:57:58.194+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 404, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 462, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "pg_type_typname_nsp_index"
DETAIL:  Key (typname, typnamespace)=(buah_id_seq, 2200) already exists.

[2024-05-02T22:57:58.302+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=17_dag_buah, task_id=create_buah_table, execution_date=20240424T000000, start_date=20240502T225754, end_date=20240502T225758
[2024-05-02T22:57:58.511+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 5 for task create_buah_table (duplicate key value violates unique constraint "pg_type_typname_nsp_index"
DETAIL:  Key (typname, typnamespace)=(buah_id_seq, 2200) already exists.
; 344)
[2024-05-02T22:57:58.609+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-02T22:57:58.665+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1296: AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
  result = cls.__new__(cls)

[2024-05-02T22:57:58.775+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-02T22:57:58.829+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
